# Generated by Django 5.2.8 on 2025-11-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_app', '0002_delete_patientdata_delete_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название исследования')),
                ('drug_name', models.CharField(max_length=100, verbose_name='Название препарата')),
                ('med', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тестируемый препарат')),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(verbose_name='ID пациента')),
                ('wellbeing_score', models.IntegerField(verbose_name='Оценка самочувствия')),
                ('drug_taken', models.CharField(choices=[('Плацебо', 'Плацебо'), ('Препарат', 'Препарат')], max_length=20, verbose_name='Принимаемый препарат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.study', verbose_name='Исследование')),
            ],
        ),
    ]
